# This is a basic workflow to help you get started with Actions
name: SynctToLambda
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events
  push:
    paths: # and only changes to the public folder
      - 'EtsyPollingTransactions.py'
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/s3-sync
    steps:
      - uses: actions/checkout@main
      - name: Deploy code to Lambda Function
        uses: cmd-not-found/aws-lambda-py39@main
        with:
          lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          lambda_region: ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


    
